### ISSUE TITLE
在基因组覆盖深度图中隐藏过短序列

### ISSUE THREAD

**Issue by jzhang-dev** [CycloneSEQ-Bioinformatics/Bamboo#10]
如图，部分基因组可能包含非常短的序列，这些序列按照目前的展示方法无法被有效展示，反倒会占用大量屏幕空间，不如将其隐藏。例如，可以隐藏长度小于最长的序列的1%的序列。

![image](https://github.com/CycloneSEQ-Bioinformatics/Bamboo/assets/56027973/cea3768e-60bf-4759-947c-573e843c0e98)

**Comment by Ming-Lian** [comment]
[#7](https://github.com/CycloneSEQ-Bioinformatics/Bamboo/issues/7)中已完成对应的优化
