### ISSUE TITLE
Homopolymer 长度分布图中，每一行的总和不等于100

### ISSUE THREAD

**Issue by jzhang-dev** [CycloneSEQ-Bioinformatics/Bamboo#11]
如图，部分情况下，Homopolymer 长度分布图中，每一行的总和不等于100。

<img width="769" alt="image" src="https://github.com/CycloneSEQ-Bioinformatics/Bamboo/assets/56027973/3e983d3b-f231-4447-ab7b-74c8702b9ada">

**Comment by jzhang-dev** [comment]
<img width="745" alt="image" src="https://github.com/CycloneSEQ-Bioinformatics/Bamboo/assets/56027973/d207abc6-80a4-4359-b794-97808dd70186">

**Comment by Ming-Lian** [comment]
该bug已修复：
- 修复前

    ![image](https://github.com/CycloneSEQ-Bioinformatics/Bamboo/assets/33211232/e90ecab4-170f-40ea-87f7-ea1f910c4e9c)

- 修复后

    ![image](https://github.com/CycloneSEQ-Bioinformatics/Bamboo/assets/33211232/38e8a969-aeb8-4a5a-a064-8af9375c53df)

*注：每行的加和应该<=100

**Comment by jzhang-dev** [comment]
Fixed in Bamboo v0.1.4
