### ISSUE TITLE
Heteropolymer 分布图与实际情况不符

### ISSUE THREAD

**Issue by jzhang-dev** [CycloneSEQ-Bioinformatics/Bamboo#13]
如图，部分情况下，Heteropolymer 分布图奇数长度序列的丰度较高，可能与实际情况不符。

![image](https://github.com/CycloneSEQ-Bioinformatics/Bamboo/assets/56027973/f005bdbe-1fbf-45b3-bfc0-03e57e826dc6)

**Comment by chsmiss** [comment]
# 已解决，在v0.1.4中会修复。
## 具体错误及改动
polymer：
    # 向左延伸，直到找到不同的碱基
    #while start > 0 and read_seq[start - 1] == read_seq[start+1] and read_seq[start - 2] == read_seq[start]:
    while start > 0 and read_seq[start - 1] == read_seq[start + 1]:
        start -= 1

**Comment by jzhang-dev** [comment]
Fixed in Bamboo v0.1.4
