### ISSUE TITLE
在文档中说明 read quality 和 mean base quality 的区别

### ISSUE THREAD

**Issue by jzhang-dev** [CycloneSEQ-Bioinformatics/Bamboo#3]
如下图，图 1 表示 read quality，是先将base quality 换算为错误率，然后再平均；图 2 表示 mean base quality，是 base quality 直接取平均。应该在文档和图注中说明这一差别，避免引起误解。

图 1:

![7371719988745_ pic](https://github.com/CycloneSEQ-Bioinformatics/Bamboo/assets/56027973/2002d69a-8d9a-423e-9916-a551c6b2e108)

图2:

<img width="977" alt="image" src="https://github.com/CycloneSEQ-Bioinformatics/Bamboo/assets/56027973/84db36f5-b3cc-4e95-991d-a25120a5a663">

**Comment by Ming-Lian** [comment]
已解决
