### ISSUE TITLE
染色体覆盖深度图标注有误

### ISSUE THREAD

**Issue by jzhang-dev** [CycloneSEQ-Bioinformatics/Bamboo#4]
如下图，染色体的标注顺序和实际长度不符。

![image](https://github.com/CycloneSEQ-Bioinformatics/Bamboo/assets/56027973/6e5626f2-6361-473b-b603-e3be8d280e98)

**Comment by Ming-Lian** [comment]
染色体的标注顺序已调整正确，bug已排除
