### ISSUE TITLE
建议对覆盖深度曲线进行平滑处理

### ISSUE THREAD

**Issue by jzhang-dev** [CycloneSEQ-Bioinformatics/Bamboo#7]
如图，目前输出的覆盖深度曲线波动较大，难以反映整体趋势，建议对曲线进行平滑处理，平滑程度应根据染色体长度智能选择。

![image](https://github.com/CycloneSEQ-Bioinformatics/Bamboo/assets/56027973/ac13e73a-21fa-4730-8825-f538e1504eb0)

**Comment by Ming-Lian** [comment]
已优化：

- 优化前

    ![image](https://github.com/user-attachments/assets/19177d27-ef4e-4b60-914f-c2c1a39b9a43)

- 优化后

    ![image](https://github.com/user-attachments/assets/db8fd736-542a-4ec6-8da2-7ade88655e91)

优化要点：

- 根据最长染色体来确定bin_size，要求最长染色体的bin数不超过1000个
- 将y_max和y_delta统一，避免之前由于y_delta<y_max带来的相邻染色体之间的串扰
- 过滤过段的染色体的展示，要求染色体的bin数不少于100个bin

**Comment by jzhang-dev** [comment]
@Ming-Lian 最小 bin 数量设置为 100 相当于忽略染色体长度为最长染色体长度的10%以下的染色体，我觉得有些过于严格了。是否可以改为最小 bin 数量10或20？

**Comment by Ming-Lian** [comment]
确实，已将最小 bin 数量设为10

**Comment by jzhang-dev** [comment]
@Ming-Lian 

<img width="244" alt="image" src="https://github.com/user-attachments/assets/a42617fe-86d5-4244-b590-36c4e4acdee3">

此处设置最大覆盖深度 ymax = 3 ，我觉得有些小，因为现实情况下，部分区域覆盖深度常常会达到 6 以上，见下图：

（注：下图为 v0.1.5 版本， ymax = 6, y_delta = 3）

<img width="813" alt="image" src="https://github.com/user-attachments/assets/710124cd-dd67-4d10-9bdd-c6e2b5c36840">

不过，如果将 ymax 设为 6，又会导致深度小于 1 的区域看不清楚。据此，我觉得允许相邻染色体的曲线有所重叠（即将 ymax 和 y_delta 分开）是一个较好的折中方案。在曲线平滑处理后，应当只有少部分区域的曲线会产生重叠，对视觉效果影响不大。

另一个方案是将该图的高度增加，或者拆为两列，也可解决不同区域深度相差过大的问题。

**Comment by Ming-Lian** [comment]
设置ymax本身就是为了减小极端高深度区域的影响，又想保留其异常高深度的趋势而采取的折中方案，设置成ymax=3确实不太能看出来这种趋势，设置成ymax=6的话，图像过于稀疏而且主体要表现的1看不出来，这么看允许重叠确实是唯一解了

但是允许相邻染色体的曲线有所重叠，这样呈现的结果是否会让用户觉得，这个图的展示有点bug？

**Comment by jzhang-dev** [comment]
有道理。那也可以考虑设置 ymax = 4，之后在测序深度超过 4  的地方显示一个标记，我记得IGV就是这样处理的。
