### ISSUE TITLE
读长分布图 bin 数量过少

### ISSUE THREAD

**Issue by jzhang-dev** [CycloneSEQ-Bioinformatics/Bamboo#8]
如图，当读长较短时，读长分布图的bin可能过于稀疏；建议固定 bin 的总数，如 bins = 100

<img width="723" alt="image" src="https://github.com/CycloneSEQ-Bioinformatics/Bamboo/assets/56027973/0fe4091e-9ffd-465c-a3b3-4296dc07b5e5">

**Comment by Ming-Lian** [comment]
该问题已优化：
![image](https://github.com/CycloneSEQ-Bioinformatics/Bamboo/assets/33211232/8d31e694-8d36-46bd-93b0-564da757084d)
- 支持NGS短reads的情况
- 将bins数量固定为50个
